version: '3.7'
services:
  mb2:
    container_name: mb2-server
    image: pvillaverde/moviebattles:latest
    restart: always
    ports:
      - "0.0.0.0:29070:29070/udp"
    volumes:
      - /srv/moviebattles/MBII/:/opt/openjk/MBII
    environment:
      sv_hostname: Mb2 server
      g_motd: test 
      #discord: rkcXvX7
      rconpassword: patata
      # Calculate permissions config: https://puppytine.github.io/
      g_smodAdminPassword_1: potatoe
      g_smodConfig_1: 65535
      # g_password: patata